### ISSUE TITLE
Can i open a image from gee and change to matrix in jupyter

### ISSUE THREAD

**Issue by xiaoxiaokuishu** [giswqs/earthengine-py-notebooks#2]
I performed below：
ds = gdal.Open('COPERNICUS/S2_SR20170328T083601_20170328T084228_T35RNK.tif')
myarray = np.array(ds.GetRasterBand(1).ReadAsArray())
But fails to open it.

Is there other way to achieved my purpose.

**Comment by giswqs** [comment]
Earth Engine images are [server-side objects](https://developers.google.com/earth-engine/client_server). There is no way you can open Earth Engine images directly using GDAL. Some workarounds include exporting the image to Google Drive or extracting a small subset as an Numpy array. See this [example](https://github.com/giswqs/geemap/blob/master/examples/notebooks/11_export_image.ipynb).  

![](https://i.imgur.com/RonLr0j.gif)
