### ISSUE TITLE
Scripts in "HowEarthEngineWorks" seem to be template

### ISSUE THREAD

**Issue by TimNagle-McNaughton** [giswqs/earthengine-py-notebooks#6]
Noticed that the scripts in /HowEarthEngineWorks don't have what (I assume) is meant to be the meat of the content. Maybe I'm missing something obvious?

**Comment by giswqs** [comment]
The `HowEarthEngineWorks` section comes from the Earth Engine Documentation https://developers.google.com/earth-engine/guides/concepts_overview. This section is mostly descriptive information without complete examples. You are welcome to convert any GEE JavaScript to Python using the geemap GUI without coding.   

https://user-images.githubusercontent.com/5016453/108772532-1c134300-752b-11eb-9684-bed4fe9c2169.mp4
