### ISSUE TITLE
Downloading Large Images Mosaic from GEE 

### ISSUE THREAD

**Issue by MrZombie69232** [giswqs/earthengine-py-notebooks#9]
Hi Professor,
I hope you are doing good . 
I was creating a mosaic for larger area from sentinel 2 collection . Isn't there a way to download those images by chipping into smaller ones ? There is a limit of 1gb but I was trying to download whole cloud free mosaic . 

Thank you for your help !

**Comment by giswqs** [comment]
You can download to Google Drive. See https://geemap.org/notebooks/11_export_image/

**Comment by MrZombie69232** [comment]
The data is around 50 GB and google drive doesn't have that much space . Isn't there a way I can download it to local machine by breaking into tiles or chipping it ?

**Comment by giswqs** [comment]
No. Large files cannot be downloaded directly to a local computer. You will need Google Drive to Google Cloud Storage.
